---
- name: Add users to groups
  hosts: all
  become: true
  gather_facts: false
  vars_files:
    - vars.yml

  tasks:
    - name: Add users to groups
      user:
        name: "{{ item.name }}"
        groups: "{{ item.groups }}"
        append: yes
      loop: "{{ users }}"
