---
- name: Install and configure Jenkins
  hosts: "{{ jenkins_host }}"
  become: yes
  remote_user: "{{ jenkins_remote_user }}"
  become_user: "{{ jenkins_become_user }}"
  vars_files:
    - vars.yml
  tasks:
  - name: Download Long Term Jenkins release
    get_url:
      url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
      dest: /etc/yum.repos.d/jenkins.repo

  - name: Import jenkins key from url
    ansible.builtin.rpm_key:
      state: present
      key: "{{ jenkins_key_url }}"

  - name: yum update
    yum:
      name: '*'
      state: latest

  - name: Install java
    yum:
      name: java-11*
      state: present

  - name: Install jenkins
    yum:
      name: jenkins
      state: latest

  - name: daemon-reload to pick up config changes
    ansible.builtin.systemd:
      daemon_reload: yes

  - name: Start jenkins
    ansible.builtin.systemd:
      name: jenkins
      state: started
  - name: Start firewalld service
    systemd:
      name: firewalld
      state: started
      enabled: yes

  - name: Allow incoming traffic on port 8080
    firewalld:
      port: "8080/tcp"
      permanent: yes
      immediate: yes
      state: enabled
  - name: Cat file contents
    ansible.builtin.shell:
      cmd: "cat /var/lib/jenkins/secrets/initialAdminPassword"
    register: innitialpass
  - name: Print Jenkins default password
    debug:
      msg: "Jenkins default password: {{ innitialpass.stdout }}"
