---
- name: Create groups
  hosts: all
  become: true
  gather_facts: false
  vars_files:
    - var.yml

  tasks:
    - name: Create groups
      group:
        name: "{{ item.name }}"
        state: "{{ item.state | default('present') }}"
        system: "{{ item.system | default(false) }}"
      loop: "{{ groups }}"